#!/bin/bash

floating=$(hyprctl activewindow -j | jq '.floating')
window=$(hyprctl activewindow -j | jq '.initialClass' | tr -d "\"")

function toggle() {
  width=$1
  height=$2

  hyprctl dispatch "hl.dsp.window.float({ action = 'toggle' })"
  hyprctl dispatch "hl.dsp.window.resize({ x = 1000, y = 600, exact = true })"
  hyprctl dispatch "hl.dsp.window.center()"
}

function untoggle() {
  hyprctl dispatch "hl.dsp.window.float({ action = 'toggle' })"
}

function handle() {
  width=$1
  height=$2

  if [ "$floating" == "false" ]; then
    toggle "$width" "$height"
  else
    untoggle
  fi
}

case $window in
kitty) handle "50%" "55%" ;;
*) handle "65%" "70%" ;;
esac
